name:                TirelessTracker
version:             0.1.0.0
github:              "githubuser/TirelessTracker"
license:             BSD3
author:              "Liam Frye-Mason"
maintainer:          "lfryemason@unm.com"
copyright:           "2018 Frye-Mason"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TirelessTracker#readme>

dependencies:
- base >= 4.7 && < 5
- time
- aeson
- text

library:
  source-dirs: src

executables:
  TirelessTracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TirelessTracker

tests:
  TirelessTracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TirelessTracker
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - tasty-quickcheck
    - tasty-golden
